### ISSUE TITLE
Race condition in scheduleFolderSyncOperations

### ISSUE THREAD

**Issue by steveshepard** [jessegrosjean/DropboxSync#4]
I believe there are some race conditions in [FolderSyncPathOperation scheduleFolderSyncOperations]. If both the local copy and the server copy of a file is modified, operations on the path will be in more than one operation queue (Delete, Get, Put). The NSOperations in these queues are concurrent, and you don't have any guarantees on which will complete first.

For example, foo.txt is modified locally and on the server, the scheduleFolderSyncOperations method will put a GetPathOperation on the getOperationQueue and a PutPathOperation on the putOperationQueue. 

If the "get" operation finishes before the "put" operation starts, the local mods will be moved aside and replaced by the server mods. When the  "put" operation starts, it will push the just-downloaded changes up to the server instead of the local changes.

One solution would be to modify scheduleFolderSyncOperations so that the conflicts are handle separately.

**Comment by jessegrosjean** [comment]
I've just pushed a test that reproduces this case 'testModifyConflict', and you are correct both a get and pull are scheduled.
