### ISSUE TITLE
PathController shouldn't retain its delegate

### ISSUE THREAD

**Issue by steveshepard** [jessegrosjean/DropboxSync#5]
By convention, controllers don't retain their delegates. The delegate property of PathController

```
@property(nonatomic, retain) id <PathControllerDelegate> delegate;
```

should probably be

```
@property(nonatomic, assign) id <PathControllerDelegate> delegate;
```

and the [delegate release] in -[PathController dealloc] should be removed.

**Comment by jessegrosjean** [comment]
Yes, thanks!
